//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_accounts()
        {
            this.tbl_personalInformations = new HashSet<tbl_personalInformations>();
            this.tbl_requirements = new HashSet<tbl_requirements>();
        }
    
        public int account_id { get; set; }
        public string account_email { get; set; }
        public Nullable<int> account_status { get; set; }
        public string account_password { get; set; }
        public Nullable<int> account_type { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual tbl_companies tbl_companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_personalInformations> tbl_personalInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_requirements> tbl_requirements { get; set; }
    }
}
